### ISSUE TITLE
Points to Tachiyomi Google Analytics account

### ISSUE THREAD

**Issue by arkon** [aniyomiorg/aniyomi-website#165]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1. Have deployed website

### Expected behavior

Collected analytics data is accessible by Aniyomi maintainers.

### Actual behavior

Notice that analytics data goes to a black hole that you can not access.

### Other details

This should be changed (or removed entirely): https://github.com/aniyomiorg/aniyomi-website/blob/2d51a4df7185e1cba294d7071f02a142cba00c4c/src/.vuepress/config/plugins.js#L30

**Comment by jmir1** [comment]
thanks
