### ISSUE TITLE
will you launch aniyomi on windows

### ISSUE THREAD

**Issue by demoniccoder1** [aniyomiorg/aniyomi-website#209]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

i an using a windows laptop and i would like to use aniyomi on windows without any use of emulators

**Comment by jmir1** [comment]
No Aniyomi can't be used on Windows without some sort of emulation because it is an Android app.
This is also not the right place to ask questions like this. This is the repository for the wesbite aniyomi.org.
