### ISSUE TITLE
Stable download button borken lol

### ISSUE THREAD

**Issue by hollowshiroyuki** [aniyomiorg/aniyomi-website#217]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

1. Go to https://aniyomi.org/download
2. Press the "Stable" button
3. ???
4. Profit

### Expected behavior

The download of the cursed version should start.

### Actual behavior

Nothing happens.

### Other details

The link seems to not be generated ??

![image](https://github.com/aniyomiorg/aniyomi-website/assets/35398794/023e06d5-a3f6-4901-93bb-7860221f0b1b)

**Comment by jmir1** [comment]
fixed by dd04ed2
(i think, i haven't tested it lmao)
