### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by borochele** [aniyomiorg/aniyomi-website#222]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

### Steps to reproduce

I have this problem. I hope that it will solved.

### Expected behavior

When i try to refresh, it shouldn’t appear and will get update of anime or manga in library.

### Actual behavior

When i try to refresh, it appear and didn’t get update.

### Other details

![Screenshot_20240405_144534](https://github.com/aniyomiorg/aniyomi-website/assets/48358836/2c259f20-0df3-418e-b506-41a63363ecc6)

**Comment by jmir1** [comment]
Classroom of the Elite sounds like a trash anime, never watched it tho

**Comment by jmir1** [comment]
Also, this is the wrong repository for this issue
